language: node_js
node_js:
- '4'
- stable

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change

deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: E3pYdpOmqrqnjM7GQTlO5Q3A8Zg4Qlr0sQrB6XN2EnEo5qAqQ8eddGHkc/B3SLGYMpUeXaAwvdgWat2Pc/Mga7IU5jTkn9rzuMJbJhRUwu4WNYOfUld2EIA+e8fRWhYEy7Q8qGTgHxPvAUtYWPUyxKqCrzbI/XDb+2oYcyXkMdEyhKADMnYcbirH/bxbMRJjScGFkOmgJszrfKS3qaVOU2+MOWRoPqC5+IoAmGsdbDN2AULtyaVRTP180CAjC24hDEXCB4kxwb9qmGwS9YYJKnd02MfiMbd2uTzftwWJBXCyVHVxk2sagFoaOCzWkiyuLLVaW+80tUjWRTgEzRvhPCG6UqZ3w0sza0Ux8k3f2duKZs3WUTZ/omEIJOwuxXaREC+I6AZ/9lABGh45N9jLce5FL2iaDBhWumW0aqUTWtwIhHwUK7v+FPU6IuRRZusx1Pd4Ztm4itjTdfhME6C0FYM6JZcskl8+g2ORjok3wnCaUn/kNCrkcEetPiUfu4/pYfk6uWYuI0V4MchWGbomnhigt50CU6QCX3eC4mo/lVhGjvBYud8L7q+mx/yhTqcidcUc4fb7Ibj5i1baeGTU6540GGpkffgWJlDRtaJKyPUdJkrUUHGZS4H2467bNVHHQMLAvjBw4qCkrfoht7pS9gCkAXqMFt59pJ85IFclD1A=
  on:
    tags: true
    repo: trailsjs/trails-model
    node: stable
